### PR TITLE
Rename `Val.__raw__` to `Val._raw`

### PR DESCRIPTION
**Pull request by fitzgen**
Stylistically we shouldn't use double under for non-builtin fields.

### CODE REVIEW

**Comment by whitequark** [comment]
(It's not just style, right? The way dunder fields are treated in Python is roughly equivalent to how defining a function called `is\w` in C is undefined behavior.)

**Comment by fitzgen** [comment]
> (It's not just style, right? The way dunder fields are treated in Python is roughly equivalent to how defining a function called `is\w` in C is undefined behavior.)

Perhaps! Its been about a decade since I seriously wrote any python, other than for little one-off scripts.

**Comment by whitequark** [comment]
In theory, CPython can add new ones at any time and so break any user code that used these for its own purposes. In practice there seems to be an unspoken agreement that libraries are allowed to grab names from that namespace in exceptional cases, but I'd still just treat them all as potential future UB.

**Comment by fitzgen** [comment]
I see there are a few other similar things, so I will fix those in another commit here.

**Comment by alexcrichton** [comment]
Ah yeah I think this is me misunderstanding things, and at least the doc generators used here recognizes "leading underscore is private" which is the intention for all these fields anyway, so sounds good. Thanks @fitzgen!

**Pull request merged**
